version: '3.9'
services:
  
  # Application
  app:
      build:
          dockerfile: app.local.dockerfile
      ports: 
        - 3000:3000 #for vite
      volumes:
        - ./src:/var/www
  # Web Server
  webnginx:
      build:
          dockerfile: web.local.dockerfile
      volumes:
          - ./src:/var/www
  db:
      image: postgres:14.4-alpine
      restart: always
      command: ["postgres", "-c", "log_statement=all"]
      environment:
        - POSTGRES_DB=stats_pro
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      ports:
        - '5432:5432'
      volumes: 
        - db:/var/lib/postgresql/data
  stripe:
      image: stripe/stripe-cli
      environment:
        - STRIPE_API_KEY=${STRIPE_SECRET}
      command: listen --forward-to http://webnginx/stripe/webhook
      volumes:
        - stripe:/var/lib/stripe
volumes:
  db:
    driver: local
  stripe:
    driver: local