export const subscriptionPlans = [
    {
        'name': 'Free',
        'priceId': 'free',
        'productId': 'free',
        'price': '$0.00',
        'isRecommended': false,
        'maxEvents': 5000,
        'maximumSites': 1,
        'description': 'Great to evaluate Marble or for just a small site. Free to use for as long as you want. No credit card required!',
        'isFree': true,
    },
    {
        'name': 'Entrepreneur',
        'priceId': import.meta.env.VITE_STRIPE_ENTREPRENEUR_PRICE_ID,
        'productId': import.meta.env.VITE_STRIPE_ENTREPRENEUR_PRODUCT_ID,
        'price': '$10.00',
        'isRecommended': false,
        'maxEvents': 100000,
        'maximumSites': 2,
        'description': 'Perfect for starting out with Marble Metrics on a couple of websites with lots of room to grow.',
        'isFree': false,
    },
    {
        'name': 'Pro',
        'priceId': import.meta.env.VITE_STRIPE_PROFESSIONAL_PRICE_ID,
        'productId': import.meta.env.VITE_STRIPE_PROFESSIONAL_PRODUCT_ID,
        'price': '$15.00',
        'isRecommended': true,
        'maxEvents': 200000,
        'maximumSites': 10,
        'description': 'For professionals who want to start integrating Marble Metrics into multiple websites with high traffic.',
        'isFree': false,
    },
    {
        'name': 'Pro Plus',
        'priceId': import.meta.env.VITE_STRIPE_PROFESSIONAL_PLUS_PRICE_ID,
        'productId': import.meta.env.VITE_STRIPE_PROFESSIONAL_PLUS_PRODUCT_ID,
        'price': '$30.00',
        'isRecommended': false,
        'maxEvents': 500000,
        'maximumSites': 50,
        'description': 'For professionals getting serious about adding Marble Metrics to many websites with high traffic.',
        'isFree': false,
    }
];
