export const subscriptionPlans = [
    {
        'name': 'Free',
        'priceId': 'free',
        'productId': 'free',
        'price': '$0.00',
        'isRecommended': false,
        'maxEvents': 5000,
        'maximumSites': 1,
        'description': 'Perfect to evaluate Marble or for just a small site',
        'isFree': true,
    },
    {
        'name': 'Entrepreneur',
        'priceId': import.meta.env.VITE_STRIPE_ENTREPRENEUR_PRICE_ID,
        'productId': import.meta.env.VITE_STRIPE_ENTREPRENEUR_PRODUCT_ID,
        'price': '$10.00',
        'isRecommended': false,
        'maxEvents': 100000,
        'maximumSites': 2,
        'description': 'Perfect for new ideas with a small base and looking for quick explosive growth.',
        'isFree': false,
    },
    {
        'name': 'Pro',
        'priceId': import.meta.env.VITE_STRIPE_PROFESSIONAL_PRICE_ID,
        'productId': import.meta.env.VITE_STRIPE_PROFESSIONAL_PRODUCT_ID,
        'price': '$15.00',
        'isRecommended': true,
        'maxEvents': 200000,
        'maximumSites': 10,
        'description': 'The best plan for a growing business looking to maximize potential and find new customers.',
        'isFree': false,
    },
    {
        'name': 'Pro Plus',
        'priceId': import.meta.env.VITE_STRIPE_PROFESSIONAL_PLUS_PRICE_ID,
        'productId': import.meta.env.VITE_STRIPE_PROFESSIONAL_PLUS_PRODUCT_ID,
        'price': '$30.00',
        'isRecommended': false,
        'maxEvents': 500000,
        'maximumSites': 50,
        'description': 'For professional marketers looking to quickly grow multiple accounts.',
        'isFree': false,
    }
];
