export const subscriptionPlans = [
    {
        'name': 'Free',
        'priceId': 'free',
        'productId': 'free',
        'price': '$0.00',
        'isRecommended': false,
        'maxEvents': 50000,
        'maximumSites': 1,
        'description': 'Great to evaluate StatsPro or for just a small site. Free to use for as long as you want. No credit card required!',
        'isFree': true,
    },
    {
        'name': 'Entrepreneur',
        'priceId': import.meta.env.VITE_STRIPE_ENTREPRENEUR_PRICE_ID,
        'productId': import.meta.env.VITE_STRIPE_ENTREPRENEUR_PRODUCT_ID,
        'price': '$15.00',
        'isRecommended': false,
        'maxEvents': 200000,
        'maximumSites': 5,
        'description': 'Perfect for starting out with StatsPro on a few websites with lots of room to grow.',
        'isFree': false,
    },
    {
        'name': 'Pro',
        'priceId': import.meta.env.VITE_STRIPE_PROFESSIONAL_PRICE_ID,
        'productId': import.meta.env.VITE_STRIPE_PROFESSIONAL_PRODUCT_ID,
        'price': '$25.00',
        'isRecommended': true,
        'maxEvents': 500000,
        'maximumSites': 50,
        'description': 'For professionals who want to start integrating StatsPro into multiple websites with high traffic.',
        'isFree': false,
    }
];
