on:
  push:
    branches: [ staging ]
  workflow_dispatch:
name: Build Staging
jobs:
  deploy-staging:
    name: "Deploy Staging"
    uses: ./.github/workflows/build.yml
    with:
      environment: staging
    secrets: inherit
    concurrency:
      group: "staging"
      cancel-in-progress: false